language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install pep8 --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E111,E128,E121,W291 urlizr"
  - "cp settings.py local_settings.py"
script:
  - python manage.py test
