language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.4.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E111,E128,E121,W291 front"
  - "pep8 --exclude=migrations --ignore=E501,E225,E111,E128,E121,W291 api"
  - pyflakes -x W front